CREATE TABLE [Streams]
(
    [StreamId] [UNIQUEIDENTIFIER] PRIMARY KEY,
	[Name] [NVARCHAR](256) NOT NULL UNIQUE,
	[Version] [INT] NOT NULL CHECK ([Version] >= (0)),
	[CreatedAt] [DATETIMEOFFSET](7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
	[UpdatedAt] [DATETIMEOFFSET](7) NULL
);

CREATE TABLE [Snapshots]
(
    [SnapshotId] [UNIQUEIDENTIFIER] PRIMARY KEY,
	[StreamId] [UNIQUEIDENTIFIER] NOT NULL FOREIGN KEY REFERENCES [Streams]([StreamId]),
	[Description] [NVARCHAR](256) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
	[Version] [INT] NOT NULL CHECK ([Version] >= (0)),
	[CreatedAt] [DATETIMEOFFSET](7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
	UNIQUE ([StreamId], [Version])
);

CREATE TABLE [Events] 
(
    [EventId] [UNIQUEIDENTIFIER] PRIMARY KEY,
	[StreamId] [UNIQUEIDENTIFIER] NOT NULL FOREIGN KEY REFERENCES [Streams]([StreamId]),
	[Type] [NVARCHAR](256) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
	[Version] [INT] NOT NULL CHECK ([Version] >= (0)),
	[CreatedAt] [DATETIMEOFFSET](7) NOT NULL DEFAULT (SYSDATETIMEOFFSET()),
	UNIQUE ([StreamId], [Version])
);